

CREATE TABLE IF NOT EXISTS users
(
    user_id     BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR   NOT NULL ,
    email       VARCHAR   NOT NULL
);
CREATE TABLE IF NOT EXISTS orders
(
    order_id        BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    foreign_user_id BIGINT    REFERENCES users(user_id),
    name            VARCHAR   NOT NULL,
    total_amount    INT       NOT NULL,
    status          VARCHAR   NOT NULL
)
