create TABLE IF NOT EXISTS department
(
    department_id       BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR   NOT NULL
);

create TABLE IF NOT EXISTS employee
(
    employee_id       BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id     BIGINT    REFERENCES department(department_id),
    first_name        VARCHAR   NOT NULL,
    last_name         VARCHAR   NOT NULL,
    position          VARCHAR   NOT NULL,
    salary            INT       CHECK(salary > 0)
);



