create TABLE IF NOT EXISTS users
(
    user_id         BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR   NOT NULL,
    email           VARCHAR   NOT NULL ,
    password        VARCHAR   NOT NULL,
    role            INT
);


