
server:
  port: 8081
#  port: 8443
#  ssl:
#      enabled=true:

jwt:
  lifetime: 30m
  secret: mySecretKey12345677890gfjhlyjhfvghlftydddtydryjetyjht3465gdfgIGUIG

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/securitysecondDB
    username: user
    password: password
