
CREATE TABLE IF NOT EXISTS customers
(
    customer_id          BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                 VARCHAR   NOT NULL,
    email                VARCHAR   NOT NULL ,
    phone                VARCHAR   NOT NULL
);

CREATE TABLE IF NOT EXISTS orders
(
    order_id               BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id            BIGINT    REFERENCES customers(customer_id),
    address                VARCHAR   NOT NULL,
    price                  INT       CHECK( price >= 0 ),
    status                 INT       NOT NULL
);

CREATE TABLE IF NOT EXISTS products
(
    product_id         BIGINT     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               VARCHAR    NOT NULL,
    description        VARCHAR,
    price              INT        CHECK( price >= 0 ),
    quantity_in_stock  INT        CHECK( quantity_in_stock >= 0 )
);

CREATE TABLE IF NOT EXISTS orders_products
(
    id             BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id       BIGINT    REFERENCES orders(order_id) ON DELETE CASCADE,
    product_id     BIGINT    REFERENCES products(product_id) ON DELETE CASCADE,
    quantity       BIGINT    CHECK( quantity > 0 )
--    PRIMARY KEY ( order_id,product_id )
);
