
CREATE TABLE IF NOT EXISTS books
(
    book_id           BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title             VARCHAR   NOT NULL,
    author            VARCHAR   NOT NULL ,
    publication_year   INT
);
